import Link from 'next/link';
export function Inline({text}:{text:string}){const regex=/\[([^\]]+)\]\((\/[^)]*|https?:\/\/[^)]+)\)/g;const parts=[];let start=0;for(const m of text.matchAll(regex)){parts.push(text.slice(start,m.index));parts.push(m[2].startsWith('/')?<Link key={m.index} href={m[2]}>{m[1]}</Link>:<a key={m.index} href={m[2]} rel="noopener noreferrer" target="_blank">{m[1]}</a>);start=m.index!+m[0].length}parts.push(text.slice(start));return <>{parts}</>}
export function Diagram({type}:{type:'door'|'save'|'map'|'goals'|'platform'|'weapons'}){const sets={
door:[['Key or keycard','Own the named access item'],['Power connection','Trace and destroy its node'],['Explosive barrier','Return with explosive equipment']],
map:[['Scan a blocked route','Keep its sector and floor'],['Record the requirement','Match your next key or tool'],['Choose the return','Revisit that specific gate']],
save:[['Restoration Pod','Revival and rechargeable healing'],['Workbench','Permanent upgrades or ammo'],['Failed attempt','Spent supplies can stay spent']],
goals:[['Logbook','Creatures · Notes · Shards · Codes'],['Exploration','Every room and shuttle station'],['Equipment','Scanner · weapons · Suit Power']],
platform:[['Windows PC','Epic Games Store'],['PlayStation 5','PlayStation Store'],['Xbox Series X/S','Xbox version']],
weapons:[['Early gun routes','Habitation F1 · Factory East F2'],['Return targets','Outer Sector B2 · Lower Levels F1'],['Later gun route','Infirmary B1 after its boss']]
}[type];const captions={door:'Read the requirement before choosing an action.',map:'Keep the place and prerequisite together.',save:'Revival and replenishment are separate checks.',goals:'Track each completion category independently.',platform:'Choose the version for the device you own.',weapons:'Sector and floor are starting points; check access tools.'};return <figure className="diagram"><svg role="img" aria-label={sets.map(x=>x.join(': ')).join('; ')} viewBox="0 0 360 228"><title>{captions[type]}</title>{sets.map(([title,detail],i)=><g key={title}><rect x="1" y={1+i*76} width="358" height="69" rx="4"/><text x="16" y={29+i*76} className="diagram-title">{title}</text><text x="16" y={53+i*76} className="diagram-detail">{detail}</text></g>)}</svg><figcaption>{captions[type]}</figcaption></figure>}
export function Breadcrumb({route,title}:{route:string;title:string}){const list=[{name:'End of Abyss Guide',item:'https://endofabyss.quest/'},{name:title,item:'https://endofabyss.quest/'+route+'/'}];return <><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Guide home</Link><span aria-hidden="true">/</span><span>{title}</span></nav><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:list.map((x,i)=>({'@type':'ListItem',position:i+1,...x}))})}}/></>}
